Feature/rename_provider
codefori/vscode-rpgle pull request #266
Opened 2023-10-14 16:51 UTC by worksofliam

### Changes

Initial work to start refactoring for RPG.

### Todo

* [ ] Fix tests for `CollectReferences` change
* [ ] Implement the rename provider
* [ ] Ensure that subfields can be renamed

### Checklist

* [ ] have tested my change
* [ ] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [ ] eslint is not complaining
* [ ] have added myself to the contributors' list in the README
* [ ] **for feature PRs**: PR only includes one feature enhancement.

2023-10-14 20:33 UTC, worksofliam commented
Depends on #265 for `cache.ts` rewrite (js -> ts).

2023-10-20 22:21 UTC, chrjorgensen commented on language/models/cache.ts
> +  static refereneceByOffset(scope: Cache, offset: number): Declaration|undefined {
```suggestion
  static referenceByOffset(scope: Cache, offset: number): Declaration|undefined {
```

Simple spelling mistake...

2023-10-20 22:48 UTC, chrjorgensen requested changes
@worksofliam Looking good - did some tests using the attach RPGLE source:

- rename standalone constant declaration - OK
- rename referenced standalone constant in assignment - OK
- rename variable in declaration - OK
- rename variable in assignment - OK
- rename DS subfield  - failed, not allowed: 
![image](https://github.com/codefori/vscode-rpgle/assets/13275072/4717ce45-e7d1-4084-831b-d552a2799157) :
- rename referenced DS subfield - failed, allowed, but only renamed reference, not declaration 
![image](https://github.com/codefori/vscode-rpgle/assets/13275072/15a7117b-b72e-41b7-a440-a1dc90b2fb84)
- rename constant declaration in enumeration - failed, not allowed.
- rename referenced constant enumeration - failed: 
![image](https://github.com/codefori/vscode-rpgle/assets/13275072/86ad107f-ba49-4d8a-b4e3-9164fd696e7e) 
![image](https://github.com/codefori/vscode-rpgle/assets/13275072/a95e55c0-6781-4130-b87a-12d2bea298a4) 
![image](https://github.com/codefori/vscode-rpgle/assets/13275072/2ed272a9-4a22-4c7c-accc-8fff3906fc47)

Enough for now - in the middle of an upgrade from 7.3 to 7.5...! 😄 

[testrename.rpgle.txt](https://github.com/codefori/vscode-rpgle/files/13059021/testrename.rpgle.txt)

2023-10-26 09:45 UTC, worksofliam commented
@chrjorgensen You are amazing for your review. I missed a whole bunch of logic for definition subfield references and now it is solved (with test cases!). Thanks for your example, which I went ahead and borrowed as you will see in the commit.

Please try again and let me know what you think.

2023-10-26 11:17 UTC, chrjorgensen commented
@worksofliam I just did some new tests:

- rename standalone constant declaration - OK
- rename referenced standalone constant in assignment - OK
- rename variable in declaration - OK
- rename variable in assignment - OK
- rename DS subfield - OK now! 👍 
- rename referenced DS subfield - OK now! 👍 
- rename constant declaration in enumeration - failed:
![image](https://github.com/codefori/vscode-rpgle/assets/13275072/2874511f-2358-4a80-a801-0f796108a14e)
- rename referenced constant enumeration to completely new name - failed:
![image](https://github.com/codefori/vscode-rpgle/assets/13275072/2874511f-2358-4a80-a801-0f796108a14e)
- rename referenced constant enumeration to name with appended chars - failed: 
![image](https://github.com/codefori/vscode-rpgle/assets/13275072/b0fadfbb-ea0b-47f9-8d3a-eba3b2c752dc) 
![image](https://github.com/codefori/vscode-rpgle/assets/13275072/d75ba378-f401-4abc-a573-162a1e60f455)
![image](https://github.com/codefori/vscode-rpgle/assets/13275072/6f6d4d6e-d6d7-488b-9e11-0032e56eab4a)

And the spelling mistake `refereneceByOffset` has not yet been fixed...

2023-10-26 11:36 UTC, worksofliam commented
@chrjorgensen Errors solved and spelling fixed!

2023-10-26 12:30 UTC, chrjorgensen commented
@worksofliam 

> @chrjorgensen Errors solved and spelling fixed!

Did you miss something? I get the following errors now when typing F2:

![image](https://github.com/codefori/vscode-rpgle/assets/13275072/96cf457d-d86c-4ebd-b348-bd8544023e80)


![image](https://github.com/codefori/vscode-rpgle/assets/13275072/52ca9564-835c-48cd-a897-c3eba9fe781b)

2023-10-26 12:33 UTC, worksofliam commented
@chrjorgensen I am sorry. I didn't do a push 🙄 Try again!

2023-10-26 13:00 UTC, chrjorgensen commented
@worksofliam Approved - merge whenever you feel for it! 😃

2023-10-26 13:01 UTC, merged