Allow format to fix indent when no lint is provided
codefori/vscode-rpgle pull request #271
Opened 2023-10-27 06:56 UTC by worksofliam

### Changes

Allows the formatter (Format Document) to fix indentation without requiring a lint configuration to be defined.

### Checklist

* [x] have tested my change
* [ ] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [ ] eslint is not complaining
* [ ] have added myself to the contributors' list in the README
* [ ] **for feature PRs**: PR only includes one feature enhancement.

2023-11-06 16:18 UTC, worksofliam commented
@chrjorgensen Any chance you can give this a go for me?

2023-11-10 14:23 UTC, chrjorgensen requested changes
@worksofliam Looking good, works great! 😍 

One question: It does not take into account whether the user has chosen to indent with spaces or tabs - it always uses spaces. Would it be an idea to indent with spaces in such a situation, where there is no linter configuration and the user has chosen tabs?

I'm personally always use spaces (as everybody should! 😆) so I'm not hit by this - but it seems the most logical to me anyway...

2023-11-10 17:21 UTC, worksofliam commented
> It does not take into account whether the user has chosen to indent with spaces or tabs

Correct! I have had some bad experiences using tabs with the ILE compilers. I do believe that the tab character is different between some EBCDIC encodings whereas space is consistent.

For now, let's stick with spaces. If one or more people request support for tabs... we'll do it.

2023-11-10 17:42 UTC, chrjorgensen commented
> For now, let's stick with spaces. If one or more people request support for tabs... we'll do it.

OK with me - but to clarify, I wasn't thinking of having tabs in the source, but instead extract the tab size and convert it into corresponding number of spaces... i.e. always have spaces, but convert tabs if chosen...

2023-11-10 17:52 UTC, worksofliam commented
@chrjorgensen Sorry - my mistake!!

I remember the original reason I didn't do the conversion from tabs to spaces and it is because VS Code can already do that for the user if they so wish. I do believe if we want to do this, it will require additional work in the linter itself. I will make an issue to track it.

<img width="621" alt="image" src="https://github.com/codefori/vscode-rpgle/assets/3708366/428aba98-b8d8-474c-973e-156e41fcc46a">

2023-11-11 15:20 UTC, merged